# Generated by Django 5.2.4 on 2025-07-18 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('users', '0005_customuser_active_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='plans.plan', verbose_name='Plano Ativo'),
        ),
    ]
