# Generated by Django 5.2.4 on 2025-07-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_storeproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcart',
            name='client',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ClientCart',
        ),
    ]
